[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fog_x"
version = "0.2.0"
dependencies = [
    "numpy",
    "pillow",
    "smart_open",
    "av",
    "requests",
    "h5py",
    "tqdm",
    "pip>=25.3",
    "protobuf==3.20.3",
    "tensorflow>=2.15.0",
    "tensorflow-datasets",
    "lerobot>=0.4.0",
]
description = "An Efficient and Scalable Data Collection and Management Framework For Robotics Learning"
readme = { file = "README.md", content-type = "text/markdown" }
license-files = ["LICENSE"]
keywords = [
    "robotics",
    "data",
    "management",
    "collection",
    "framework",
    "learning",
]

[project.optional-dependencies]
hf = ["datasets"]
rtx = ["tensorflow", "tensorflow_datasets", "envlogger"]
aws = ["boto3"]
torch = ["torch"]
lerobot = ["lerobot", "datasets", "torch", "torchvision"]
all = [
    "datasets",
    "tensorflow",
    "tensorflow_datasets",
    "envlogger",
    "boto3",
    "smart_open",
    "torch",
    "torchvision",
]

[project.urls]
homepage = "https://github.com/BerkeleyAutomation/fog_x/"

[tool.setuptools.packages.find]
where = ["."]
include = ["fog_x*"]
exclude = ["data*", "tests*", "examples*", "scripts*", "docs*", "benchmarks*"]
